project:
  type: website
  output-dir: docs

website:
  title: "Isaac Young's Website"
  site-path: "/personal-isaac-young/"
  reader-mode: true
  repo-url: https://github.com/isaacy02/personal-isaac-young
  repo-actions: issue
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 
      - href: posts/index.qmd
        text: Blog

  sidebar:

    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Articles"
          href: articles/index.qmd
          contents:
          - text: "Chapter 4 Sum and Range"
            href:  articles/article_01.qmd
          - text: "Chapter 5 Everything"
            href:  articles/article_02.qmd
          - text: "Enhancement Description"
            href:  articles/article_03.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: 
          - text: "Quarto Image Add"
            href:  posts/Blog 1/index.qmd
          - text: "CSC in the NFL"
            href:  posts/Blog 2/index.qmd
          - text: "Gtown Football"
            href:  posts/Blog 3/index.qmd
          - text: "Lightsaber Colors"
            href:  posts/Blog 4/index.qmd
          - text: "Super Bowl Winner"
            href:  posts/Blog 5/index.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: true